spring:
  application:
    name: CustomAnnotationSpringboot
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringDemo
    username: postgres
    password: mysecretpassword
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8989
security:
  jwt:
    secret-key: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"
    expire: 3600000
